# Generated by Django 2.1.2 on 2019-02-23 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190223_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='startup_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
